### PR TITLE
Improve JSON syntax highlighting (Atom)

### PR DESCRIPTION
**Pull request by ramonmcros**

### CODE REVIEW

**Comment by mashaal** [comment]
🎈💎🎈

**Comment by ramonmcros** [comment]
:smile_cat:

**Comment by mashaal** [comment]
Thanks for helping, I added a credit for you in the readme- Also, I've got some upcoming emoji integration happening inside the atom editor, soon!

**Comment by ramonmcros** [comment]
Cool, you really love emoji! Thanks!

**Pull request merged**
